fallback-grpc-addr: 127.0.0.1:5050
dial-grpc-timeout: 10

jaeger:
  url: url

consul:
  addr: addr
order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

stripe-key: stripe-key
endpoint-stripe-secret: endpoint-stripe-secret

rabbitmq:
  user: guest
  password: password
  host: host
  port: port

redis:
  local:
    ip: ip
    port: 6379
    password: password
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100


mongo:
  user: mongo
  password: 123456
  host: 127.0.0.1
  port: 27017
  db-name: "order"
  coll-name: "order"

mysql:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbname: "go_pay"



