fallback-grpc-addr: 127.0.0.1:5050
dial-grpc-timeout: 10

jaeger:
  url: "http://127.0.0.1:14268/api/traces"


consul:
  addr: 116.198.246.11:8500
order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

stripe-key: stripe-key
endpoint-stripe-secret: endpoint-stripe-secret

rabbitmq:
  user: guest
  password: password
  host: host
  port: port



